config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"

  resources :rooms do
    get :posts, on: :collection
    get :search, on: :collection
  end

  resources :users, only: [:index, :show, :edit, :account, :profile, :update] do
    get :account, on: :collection
    get :profile, on: :collection
  end

  resources :reservations, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :number_people, presence: true
  validates :start_day, presence: true
  validates :end_day, presence: true

  validate :date_before_start
  validate :date_before_end

  def date_before_start
    now = Date.today
    errors.add(:end_day, "過去の日付は無効です") if (start_day < now) || (end_day < now)
  end

  def date_before_end
    errors.add(:end_day, "は開始日より後にしてください") if end_day < start_day
  end

  def amount_day
    self.end_day - self.start_day
  end
  
  def amount_price
    self.room.price * self.number_people * self.stay_day
  end
end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user
  has_many :reservations

  mount_uploader :image, ImageUploader

  validates :room_name, presence: true
  validates :room_text, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :image, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :rooms
  has_many :reservations

  mount_uploader :image, ImageUploader

  validates :username, presence: true
  validates :profile, presence: true, on: :update
  validates :image, presence: true, on: :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end

  def after_sign_in_path_for(resource)
    root_path(resource)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all.order(created_at: :desc)
  end

  def new
    @user = User.find(params[:reservation][:user_id])
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    if @reservation.valid?
      @reservation.stay_day = @reservation.amount_day
      @reservation.total_amount = @reservation.amount_price
      render "new"
    else
      if @reservation.start_day == nil || @reservation.end_day == nil || @reservation.number_people == nil
        flash.now[:alert] = "必須項目を入力してください"
      else
        if (@reservation.start_day < Date.today) || (@reservation.end_day < Date.today)
          flash.now[:alert] = "過去の日付は無効です"
        elsif @reservation.end_day < @reservation.start_day
          flash.now[:alert] = "終了日は開始日より後にしてください"
        end
      end
      render template: "rooms/show", status: :unprocessable_entity
    end
  end

  def create
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.save
      flash[:notice] = "予約しました"
      redirect_to "/reservations/#{@reservation.id}"
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @room = @reservation.room
  end

  private
  def reservation_params
    params.require(:reservation).permit(:start_day, :end_day, :stay_day, :number_people, :total_amount).merge(user_id: current_user.id, room_id: @room.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to "/rooms/posts"
    else
      flash.now[:alert] = "ルーム情報を入力してください"
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @user = current_user
  end

  def search
    if params[:address].present?
      @search = Room.where("address LIKE ? ", "%#{params[:address]}%")
    elsif params[:room_text].present?
      @search = Room.where('room_text LIKE ?', "%#{params[:room_text]}%")
    elsif (params[:address] == nil || '') || (params[:room_text] == nil || '')
      @search = Room.all
    else
      @search = Room.all
    end
  end

  def posts
    @room = Room.where(user_id: current_user.id).includes(:user).order(created_at: :desc)
  end

  private
  def room_params
    params.require(:room).permit(:room_name, :room_text, :price, :address, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def account
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def update
    @user = current_user
    if @user.id == current_user.id && @user.update(def user_params)
      redirect_to action: :profile
    else
      redirect_to action: :profile
    end
  end

  private
  def user_params
    params.require(:user).permit(:image, :username, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <title>宿泊予約サービスアプリ</title>
  </head>

  <body>
    <header class="header">
      <div class="header-inner">
        <div class="header-left-nav">
          <%= link_to root_path do %>
            <img src="/assets/logo.png" alt="サイトのロゴ画像">
          <% end %>
          <%= form_with url: search_rooms_path, local: true, method: :get do |f| %>
            <div class="header-sharch d-lg-inline-block">
              <%= f.text_field :address, class:"form-control", placeholder: "エリア" %>
              <i class="fas fa-map-marker-alt"></i>
            </div>
            <div class="header-sharch d-lg-inline-block">
              <%= f.text_field :room_text, class:"form-control", placeholder: "キーワード" %>
              <i class="fas fa-search"></i>
            </div>
            <%= f.submit "探す", class: "d-none" %>
          <% end %>
        </div>
        <div class="header-right-nav">
          <div class="nav-item d-sm-inline-block d-none">
            <% if user_signed_in? %>
              <%= current_user.username %>
            <% end %>
          </div>
          <div class="nav-item">
            <% if user_signed_in? %>
              <% if current_user.image? %>
                <%= image_tag current_user.image.thumb.url, alt: "プロフィール画像", onclick:"js_event()", class: "mx-3 p-1 host-icon nav-trigger"%>
              <% else %>
                <%= image_tag "logo.jpeg", alt: "プロフィール画像", onclick:"js_event()", class: "mx-3 p-1 host-icon nav-trigger"%>
              <% end %>

              <ul class="header-nav-menu" id="click">
                <li><%= link_to "ルーム登録", :new_room %></li>
                <li><%= link_to "予約済みルーム一覧", :reservations %></li>
                <li><%= link_to "登録済みルーム一覧", :posts_rooms %></li>
                <li><%= link_to "設定", :account_users %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              </ul>
            <% else %>
              <%= link_to "ログイン", new_user_session_path, class:"btn btn-primary my-2 mx-3" %>
              <%= link_to "登録する", new_user_registration_path, class:"btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <% if flash[:notice] %>
      <div class="notification">
        <div class="notice">Signed in successfully.</div>
      </div>
    <% elsif flash[:alert] %>
      <div class="notification">
        <div class="alert">Invalid Email or password.</div>
      </div>
    <% end %>
    
    <%= yield %>

    <footer class="footer">
      <p>© 2020 POTEPAN.INC.</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fb58181adb.js" crossorigin="anonymous"></script>

  </body>
</html>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>
    <tbody>
    <% @reservations.each do |f| %>
      <tr>
        <td>
          <%= link_to "/rooms/#{f.room_id}" do %>
            <%= image_tag f.room.image.url ,size: '240x140', class: "reservations-image" %>
          <% end %>
        </td>
        <td class="posts-name">
          <%= link_to "/rooms/#{f.room_id}" do %>
            <%= f.room.room_name %>
          <% end %>
        </td>
        <td class="posts-content"><%= f.room.room_text %></td>
        <td class="price-icon"><%= f.total_amount %></td>
        <td><%= f.start_day %></td>
        <td><%= f.end_day %></td>
        <td><%= f.created_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/new.html.erb
<div class="container reservations-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservations-new-nav">
        <h4 class="reservations-new-check-content">予約内容確認</h4>
        <h5 class="price-icon"><%= @room.price %> / 日</h5>
        <div class="reservations-new-date-select">
          <%= form_with model: @reservation, local: true do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.label :start_day, "開始日" %>
            <%= f.text_field :start_day, :readonly => true, class: "form-control mb-4" %>
            <%= f.label :end_day, "終了日" %>
            <%= f.text_field :end_day, :readonly => true, class: "form-control mb-4" %>
            <%= f.hidden_field :stay_day, value: @reservation.stay_day %>
            <h6 class="reservations-new-check-content">使用日数 : <%= @reservation.stay_day %>日</h6>
            <%= f.hidden_field :number_people, value: @reservation.number_people %>
            <h6 class="reservations-new-check-content">人数 : <%= @reservation.number_people %>人</h6>
            <%= f.label :total_amount, "合計金額" %>
            <%= f.text_field :total_amount, :readonly => true, class: "form-control mb-4" %>
            <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
            <%= f.submit :"予約を確定", class: "btn btn-primary form-control my-3" %>
            <%= link_to "ルーム詳細に戻る", :back, class: "btn btn-secondary form-control" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-md-12 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">予約した部屋</label>
            <div class="col-md-9">
              <%= link_to @room.room_name, "/rooms/#{@reservation.room_id}" %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">終了日</label>
            <div class="col-md-9">
              <%= @reservation.start_day.to_s(:date_jp) %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">終了日</label>
            <div class="col-md-9">
              <%= @reservation.end_day.to_s(:date_jp) %>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">価格</label>
            <div class="col-md-9">
              <%= @reservation.total_amount %>円
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<% @rooms.each do |room| %>
  <% room.id %>
  <% room.image %>
  <% room.room_name %>
  <% room.room_text %>
  <% room.price %>
  <% room.address %>
<% end %>

<div class="top">
  <div class="top-main">
    <div class="container">
      <div class="row col-lg-6">
        <div class="form-fream">
          <div class="form-area">
            <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
            <%= form_with url: search_rooms_path, local: true, method: :get do |f| %>
              <%= f.label :address, "エリア" %>
              <%= f.text_field :address, class:"form-control mb-4", placeholder: "東京" %>
              <%= f.submit "探す", class:"form-control btn-primary mb-4" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="panel-area m-5">
      <h1 class="section-title">おすすめのエリア</h1>
      <div class="row">
        <div class="panel-item col-lg-3 col-6">
          <span>東京</span>
          <%= link_to controller: 'rooms', action: 'search', address: "東京" do %>
            <%= image_tag "img_tokyo.jpg", class: "panel-image" %>
          <% end %>
          <div class="shadow"></div>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>大阪</span>
          <%= link_to controller: 'rooms', action: 'search', address: "大阪" do %>
            <%= image_tag "img_osaka.jpg", class: "panel-image" %>
          <% end %>
          <div class="shadow"></div>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>京都</span>
          <%= link_to controller: 'rooms', action: 'search', address: "京都" do %>
            <%= image_tag "img_kyoto.jpg", class: "panel-image" %>
          <% end %>
          <div class="shadow"></div>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>札幌</span>
          <%= link_to controller: 'rooms', action: 'search', address: "札幌" do %>
            <%= image_tag "img_sapporo.jpg", class: "panel-image" %>
          <% end %>
          <div class="shadow"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container-fiuld room-new">
  <div class="row">
    <div class="col-lg-2 room-nav room-nav-pc d-lg-block d-none">
      <ul>
        <li class="active"><a href="/rooms/new">基本情報</a></li>
      </ul>
    </div>
    <div class="col-lg-10 room-view">
      <div class="room-view-box">
        <%= form_with model: @room, class:"new-room", local: true do |f| %>
          <div class="update-content">
            <div class="room-new-row">
              <h5>ルーム情報登録</h5>
            </div>
          </div>
          <div class="update-content">
            <div class="room-new-row">
              <%= f.label :room_name, "ルーム名" , class:"col-md-3 required-a" %>
              <%= f.text_field :room_name, class:"form-control mb-4 col-mb-9", placeholder: "ルーム名を入力" %>
            </div>
          </div>
          <div class="update-content">
            <div class="room-new-row">
              <%= f.label :room_text, "ルーム紹介" , class:"col-md-3 required-a" %>
              <%= f.text_area :room_text, class:"form-control mb-4 col-mb-9", placeholder: "ルーム説明を入力" %>
            </div>
          </div>
          <div class="update-content">
            <div class="room-new-row">
              <%= f.label :price, "料金" , class:"col-md-3 required-a" %>
              <%= f.text_field :price, class:"form-control mb-4 col-mb-9", placeholder: "一日あたりの料金を入力" %>
            </div>
          </div>
          <div class="update-content">
            <div class="room-new-row">
              <%= f.label :address, "住所" , class:"col-md-3 required-a" %>
              <%= f.text_field :address, class:"form-control mb-4 col-mb-9", placeholder: "住所を入力" %>
            </div>
          </div>
          <div class="update-content">
            <div class="room-new-row">
              <%= f.label :image, "ルーム画像" , class:"col-md-3 required-a" %>
              <%= f.file_field :image, class:"mb-4 col-mb-9" %>
            </div>
          </div>
          <div class="update-content">
            <div class="room-new-row">
              <%= f.submit "登録", class:"col-md-2 btn btn-primary mx-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/posts.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="senter">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>
    <tbody>
      <% @room.each do |room| %>
        <tr>
          <td><%= link_to room_path(room) do %>
            <%= image_tag room.image.url, class: "room-posts-image" %>
          <% end %></td>
          <td class="posts-name"><%= link_to room.room_name, room_path(room) %></td>
          <td class="posts-content"><%= room.room_text %></td>
          <td class="price-icon"><%= room.price %></td>
          <td><%= room.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<div class="container-fiuld room">
  <h4 class="pb-4">検索結果 : <%= @search.count %>件</h4>

  <div class="row">
  <% @search.each do |search| %>
    <div class="col-sm-6 col-lg-4 col-xl-3">
      <div class="room-frame-inner">
        <%= link_to room_path(search) do %>
          <div class="room-image-out">
            <%= image_tag search.image.url, class: "room-image" %>
          </div>
          <div class="room-profile">
            <p class="room-profile-name"><%= search.room_name %></p>
            <p class="room-profile-city"><%= search.address %></p>
            <p class="room-profile-price price-icon"><%= search.price %></p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-md-8">
      <%= image_tag @room.image.url, class: "room-show-image" %>
      <div class="room-show-detile">
        <div class="room-show-detile-icon">
          <%= link_to root_path do %>
            <% if @user.image? %>
              <%= image_tag current_user.image.url, alt: "プロフィール画像", class: "icon-image host-icon" %>
            <% else %>
              <%= image_tag "logo.jpeg", alt: "プロフィール画像", size: "200", class: "icon-image host-icon" %>
            <% end %>
          <% end %>
        </div>
        <div class="room-show-profile">
          <p class="room-show-profile-name"><%= @room.room_name %></p>
          <p class="room-show-profile-address"><%= @room.address %></p>
        </div>
      </div>
      <p class="room-show-detile-content"><%= @room.room_text %></p>
    </div>
    <div class="col-md-4">
      <div class="room-show-nav">
        <h5 class="price-icon"><%= @room.price %> / 日</h5>
        <div class="room-show-date-select">
          <%= form_with model: @reservation, url: new_reservation_path, method: :get, class: "new-room", local: true do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.label :start_day, "開始日" %>
            <%= f.date_field :start_day, class: "form-control mb-4" %>
            <%= f.label :end_day, "終了日" %>
            <%= f.date_field :end_day, class: "form-control mb-4" %>
            <%= f.label :number_people, "人数" %>
            <%= f.number_field :number_people, class: "form-control mb-4" %>
            <%= f.submit "予約する", class: "btn btn-primary form-control" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <div class="">
      <div><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_user1.html.erb
<div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
  <ul>
    <li class="active"><%= link_to "アカウント", :account_users %></li>
    <li><%= link_to "プロフィール", :profile_users %></li>
  </ul>
</div>

app/views/shared/_user2.html.erb
<div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
  <ul>
    <li><%= link_to "アカウント", :account_users %></li>
    <li class="active"><%= link_to "プロフィール", :profile_users %></li>
  </ul>
</div>

app/views/users/account.html.erb
<div class="container-fiuld user">
  <div class="row">
    <%= render "shared/user1" %>
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3">メールアドレス</label>
            <div class="col-md-9"><%= @user.email %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
          <label class="col-md-3">パスワード</label>
            <div class="col-md-9">*********</div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <%= link_to '編集', edit_user_registration_path, class: "col-md-2 btn btn-primary mx-3" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container-fiuld user">
  <div class="row">
    <%= render "shared/user2" %>
    <div class="col-lg-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>プロフィール</h5>
          </div>
        </div>
        <%= form_with model: @user, local: true do |f| %>
          <div class="update-content">
            <div class="row">
              <div class="col-md-6 offset-md-3">
                <div class="icon-box">
                  <% if @user.image? %>
                    <%= image_tag current_user.image.url, alt: "プロフィール画像", class: "icon-image host-icon" %>
                  <% else %>
                    <%= image_tag "logo.jpeg", alt: "プロフィール画像", size: "200", class: "icon-image host-icon" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :image, "アイコン画像", class: "col-md-3 required-a" %>
              <%= f.file_field :image, class: "mb-4 col-md-9" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :username, "名前", class: "col-md-3 required-a" %>
              <%= f.text_field :username, class: "form-control mb-4 col-md-9" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :profile, "自己紹介", class: "col-md-3 required-a" %>
              <%= f.text_area :profile, class: "form-control mb-4 col-md-9", placeholder: "自己紹介" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
            <%= f.submit "更新", class: "col-md-2 btn btn-primary mx-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>